version: '3.9'

services:
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - '.:/app/client'
      - '/app/client/node_modules'
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true
