version: '3.9'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '5001:5001'
    expose:
      - "5001"
